default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: stripe_api_development

test:
  <<: *default
  database: stripe_api_test

production:
  <<: *default
  database: stripe_api_production